### ISSUE TITLE
Compiler crash in AnalyseDeclarationsTransform with baconwrap.pyx

### ISSUE THREAD

**Issue by brews** [brews/snakebacon#19]
Recent bug caught by travis-ci. Here is the log:
```
Compiling snakebacon/mcmcbackends/bacon/baconwrap.pyx because it changed.
[1/1] Cythonizing snakebacon/mcmcbackends/bacon/baconwrap.pyx
Error compiling Cython file:
------------------------------------------------------------
...
            
    Returns
    -------
    int relating to burn-in and sub-sample thinning parameters. See bacon.cpp lines 41-44 and 156.
    """
    cdef extern from "bacon.cpp":
        ^
------------------------------------------------------------
snakebacon/mcmcbackends/bacon/baconwrap.pyx:269:9: Compiler crash in AnalyseDeclarationsTransform
ModuleNode.body = StatListNode(baconwrap.pyx:1:0)
StatListNode.stats[15] = StatListNode(baconwrap.pyx:250:0)
StatListNode.stats[0] = DefNode(baconwrap.pyx:250:0,
    doc = "Run bacon MCMC on input file, and put output into outfile\n    \n    The underlying C/C++ from Bacon assumes there is a directory, 'Curve' in runtime CWD that holds special format \n    calibration curve. \n    \n    Parameters\n    ----------\n        infile : str\n            Path of existing bacon-format file to be input into MCMC.\n        outfile : str\n            Path of file where bacon MCMC results are dumped.\n        ssize : int\n            Sample size of input data.\n            \n    Returns\n    -------\n    int relating to burn-in and sub-sample thinning parameters. See bacon.cpp lines 41-44 and 156.\n    ",
    modifiers = [...]/0,
    name = '_baconmain',
    np_args_idx = [...]/0,
    num_required_args = 3,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')
File 'Nodes.py', line 427, in analyse_declarations: StatListNode(baconwrap.pyx:251:4)
File 'Nodes.py', line 495, in analyse_declarations: CDefExternNode(baconwrap.pyx:269:9,
    include_file = 'bacon.cpp')
Compiler crash traceback from this point on:
  File "/home/travis/miniconda/envs/test_env/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 495, in analyse_declarations
    env.add_include_file(self.include_file, self.verbatim_include, late)
TypeError: add_include_file() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    setup_kwargs['ext_modules'] = cythonize([bacon])
  File "/home/travis/miniconda/envs/test_env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/home/travis/miniconda/envs/test_env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: snakebacon/mcmcbackends/bacon/baconwrap.pyx

```
I can't catch this on my local machine running cython 0.26 so it must be something that has come up since cython released the current version 0.28.2.

**Comment by brews** [comment]
Just confirmed that I'm only getting this error with cython version 0.28. Prior releases have no issue as far as I can see.
